from PyQt5.QtWidgets import QWidget, QPushButton, QGridLayout, QLabel, QLineEdit, QRadioButton
class GridLayout(QWidget):
    def __init__(self):
        super().__init__()
        self.GridUI()
    def GridUI(self):
        self.resize(400, 300)
        self.move(300,300)
        self.setWindowTitle('Latihan 3')
        self.Label1 =QLabel('<b>Nama</b>')
        self.LineEdit1 =QLineEdit()
        self.Label2 =QLabel('<b>Umur</b>')
        self.LineEdit2 =QLineEdit()
        self.Label3 =QLabel('<b>Hoby</b>')
        self.LineEdit3 =QLineEdit()
        self.Label4 = QLabel('<b>Jenis Kelamin</b>')
        self.RadioButton = QRadioButton('Laki-Laki')
        self.RadioButton2 = QRadioButton('Perempuan')
        self.Button = QPushButton('Submit')
        layout =QGridLayout()
        layout.addWidget(self.Label1, 0, 0,)
        layout.addWidget(self.LineEdit1, 0, 1,1,2)
        layout.addWidget(self.Label2, 1, 0)
        layout.addWidget(self.LineEdit2, 1, 1,1,2)
        layout.addWidget(self.Label3, 2, 0)
        layout.addWidget(self.LineEdit3, 2, 1,1,2)
        layout.addWidget(self.Label4, 3,0)
        layout.addWidget(self.RadioButton, 3, 1)
        layout.addWidget(self.RadioButton2, 3, 2)
        layout.addWidget(self.Button,4,0,1,3)
        self.setLayout(layout)
